"""Update city_id field onupdate

Revision ID: 8e93e4ce6024
Revises: ba9fd48e2175
Create Date: 2024-08-27 17:12:49.314637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e93e4ce6024'
down_revision: Union[str, None] = 'ba9fd48e2175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
